'use client';

import { useEffect, useState } from 'react';

type ExportKind = 'sql' | 'json' | 'csv';
type ExportFile = {
  name: string;
  kind: ExportKind;
  size: number;
  mtime: number;
  anonymized: boolean;
  containsPhi: boolean;
};

const KIND_META: Record<ExportKind, { title: string; blurb: string; accent: string }> = {
  sql: { title: 'SQL Dump', blurb: 'Complete database as portable INSERT statements — the entire dataset.', accent: 'text-amber-400' },
  json: { title: 'JSON', blurb: 'Structured sessions with transcripts & notes (anonymized).', accent: 'text-violet-400' },
  csv: { title: 'CSV', blurb: 'Flat tables for spreadsheets and analysis.', accent: 'text-emerald-400' },
};

function humanSize(bytes: number): string {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / Math.pow(1024, i)).toFixed(i ? 1 : 0)} ${units[i]}`;
}

export default function ExportCenter() {
  const [files, setFiles] = useState<ExportFile[]>([]);
  const [available, setAvailable] = useState(true);
  const [tried, setTried] = useState<{ path: string; error: string }[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/exports')
      .then((r) => r.json())
      .then((d) => {
        setFiles(d.files || []);
        setAvailable(d.available !== false);
        setTried(d.tried || []);
      })
      .catch(() => setAvailable(false))
      .finally(() => setLoading(false));
  }, []);

  const groups: ExportKind[] = ['sql', 'json', 'csv'];

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">Bulk Export Center</h2>
        <p className="text-[var(--color-text-secondary)]">
          Download the archive as SQL, JSON, or CSV. Files are generated by the scraper and refreshed
          automatically as it runs.
        </p>
      </div>

      {loading && <p className="text-sm text-[var(--color-text-muted)]">Loading available exports…</p>}

      {!loading && !available && (
        <div className="p-4 border border-amber-500/30 rounded-lg bg-amber-500/10 text-sm space-y-2">
          <p className="font-medium">The dashboard can&apos;t see the exports folder.</p>
          <p className="text-[var(--color-text-secondary)]">
            The volume is defined in <code>docker-compose.yml</code>, but a newly-added mount only takes
            effect on a fresh container. Recreate the dashboard:
          </p>
          <pre className="text-xs bg-[var(--color-surface-3)] p-2 rounded overflow-x-auto">docker-compose up -d --build --force-recreate dashboard</pre>
          {tried.length > 0 && (
            <div className="text-xs text-[var(--color-text-muted)]">
              <p className="mb-1">Paths checked:</p>
              <ul className="list-disc pl-5 space-y-0.5">
                {tried.map((t) => (
                  <li key={t.path}>
                    <code>{t.path}</code> — {t.error === 'ENOENT' ? 'not mounted' : t.error === 'EACCES' ? 'permission denied' : t.error}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {!loading && available && files.length === 0 && (
        <div className="p-4 border border-[var(--color-surface-border)] rounded-lg bg-[var(--color-surface-2)] text-sm">
          No export files found yet. They are created after the first batch of sessions is processed.
        </div>
      )}

      {!loading && available && files.length > 0 && (
        <div className="space-y-8">
          {groups.map((kind) => {
            const group = files.filter((f) => f.kind === kind);
            if (group.length === 0) return null;
            const meta = KIND_META[kind];
            return (
              <div key={kind}>
                <h3 className={`text-lg font-bold mb-1 ${meta.accent}`}>{meta.title}</h3>
                <p className="text-xs text-[var(--color-text-muted)] mb-3">{meta.blurb}</p>
                <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
                  {group
                    .sort((a, b) => a.name.localeCompare(b.name))
                    .map((f) => (
                      <div
                        key={f.name}
                        className="p-4 border border-[var(--color-surface-border)] rounded-lg bg-[var(--color-surface-2)] flex flex-col gap-2"
                      >
                        <div className="flex items-center justify-between gap-2">
                          <span className="font-mono text-sm truncate" title={f.name}>{f.name}</span>
                          <span className="text-[10px] text-[var(--color-text-muted)]">{humanSize(f.size)}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          {f.anonymized && (
                            <span className="text-[10px] px-1.5 py-0.5 rounded bg-emerald-500/15 text-emerald-400 border border-emerald-500/30">
                              anonymized
                            </span>
                          )}
                          {f.containsPhi && (
                            <span className="text-[10px] px-1.5 py-0.5 rounded bg-rose-500/15 text-rose-400 border border-rose-500/30">
                              contains PHI
                            </span>
                          )}
                        </div>
                        <a
                          href={`/api/exports/download?file=${encodeURIComponent(f.name)}`}
                          className="mt-1 text-center px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded text-sm font-medium"
                        >
                          Download
                        </a>
                      </div>
                    ))}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
